### ISSUE TITLE
Various reflowable EPUB columns shift issues

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-navigator-kotlin#146]
On some books, when swiping through the content, the EPUB columns are shifting and are not aligned anymore. This reverts by tapping on the edges.

I could reproduce this on [oryel_1984.zip](https://github.com/readium/r2-navigator-kotlin/files/4836912/oryel_1984.zip) from this issue: https://github.com/readium/r2-navigator-kotlin/issues/145 

![Screenshot_20200629-101320](https://user-images.githubusercontent.com/58686775/85990279-11cb9400-b9f2-11ea-8499-d656b236e410.png)

**Comment by mickael-menu** [comment]
Another related issue, the columns are slightly shifting in long resources, such that the last page is not centered. For example with Gatsby:

![Screenshot_20200818-111928](https://user-images.githubusercontent.com/58686775/90495454-f012a180-e144-11ea-9560-314b977b770a.png)

**Comment by mickael-menu** [comment]
Another issue, I can move the offset of a page by pinching it, then panning it in a single gesture.
![Screenshot_20200819-162838](https://user-images.githubusercontent.com/58686775/90648045-58db4600-e239-11ea-8e33-ebad3ab4492c.png)

**Comment by johanpoirier** [comment]
I also have issues with going to a locator with an anchor fragment (i.e. `Chapitre02.html#int02-s3`).
The columns are shifted as well. Loading the webView with an URL containing an anchor is problematic. Is it CSS related?

**Comment by nidhinprathap** [comment]
@johanpoirier there's a method that's javascript getting called but the definition is missing. Please check the below-mentioned ticket.
https://github.com/readium/r2-testapp-kotlin/issues/351

For now, you can change tat and call scrollToTag method in utility.js

**Comment by johanpoirier** [comment]
> For now, you can change tat and call scrollToTag method in utility.js

Yes I did see that and I used `scrollToId` method instead. But the behaviour is sometimes odd. When the URL has an anchor, the page displayed is the one before so I'm trying to debug the issue right now.

**Comment by nidhinprathap** [comment]
ah for that can u try this

var scrollAnchor = function(id) {
        var element = document.getElementById(id);
        var elementOffset = element.scrollLeft // element.getBoundingClientRect().left works for Gutenbergs books
        if (elementOffset == 0) {
            elementOffset = element.getBoundingClientRect().left;
        }
        var offset = Math.round(window.scrollX + elementOffset);

        document.scrollingElement.scrollLeft = snapOffset(offset);
 
};
@johanpoirier can you try this

**Comment by johanpoirier** [comment]
> Another issue, I can move the offset of a page by pinching it, then panning it in a single gesture.

This is caused by those lines of code: https://github.com/readium/r2-navigator-kotlin/blob/develop/r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt#L735-L738

The `mLastMotionX` is set by the second finger down, so the `xDiff` is almost never greater than `mTouchSlop `: https://github.com/readium/r2-navigator-kotlin/blob/develop/r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt#L677

My question is: why are we mixing touch pointers values into `mLastMotionX`?

**Comment by mickael-menu** [comment]
It looks like the offset issues are caused by some rendering bug in Android's Web View, but we have a potential workaround enabled by Readium CSS: https://github.com/readium/readium-css/issues/97

**Comment by mickael-menu** [comment]
I pushed a PR which addresses the offset issue at least in my use cases, using the latest version of Readium CSS. I'm not 100% sure it fixes all of the reported offset issues.

https://github.com/readium/r2-navigator-kotlin/pull/178

Note that `utils.js` is completely rewritten, to align with the Swift version. I didn't see any regression with RTL (which didn't work anyway in my tests) but something to keep in mind in case some other issues pop up.

@johanpoirier 

> I also have issues with going to a locator with an anchor fragment (i.e. Chapitre02.html#int02-s3).
The columns are shifted as well.

This should be fixed as well, would you mind double-checking with this PR?

**Comment by johanpoirier** [comment]
thanks @mickael-menu , I test that next monday.

**Comment by johanpoirier** [comment]
> This should be fixed as well, would you mind double-checking with this PR?

I just tested it on my own app and the r2-testapp but the offset issue is still present in this case.
I fixed it on my app a few weeks ago, I'll try to put the fix in a PR tomorrow.

**Comment by mickael-menu** [comment]
> I fixed it on my app a few weeks ago, I'll try to put the fix in a PR tomorrow.

Sounds good, might be that we're using different test cases. Thanks for taking a look!
